name = "archive-api"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

kv_namespaces = [
  { binding = "CLIENTS_KV", id = "924043a9e99c48019ce1d54d6c992fda" },
  { binding = "SESSIONS_KV", id = "4fdf3c9fa73a42349a50e23531e5228c" },
  { binding = "EVENTS_KV", id = "92c5168199204840ae518b150b0c3b94" }
]

[triggers]
crons = ["*/2 * * * *"]
